Преподаватель: Артур Сапрыкин
Условие: Задача состоит в модификации кода градиентного спуска для задачи регрессии (ноутбук лекции - Gradient_descent.ipynb). Необходимо, чтобы ваш градиентный спуск мог решать задачи классификации, а именно линейной классификации и логистической регрессии.
На всякий случай напомню, что код будет разный, поэтому жду от вас две функции градиентного спуска.
Решение задачи можете найти в этой статье - https://dyakonov.org/2018/03/12/логистическая-функция-ошибки/. Там указан необходимый лосс и градиент"

In [121]:
import numpy as np
import random
from sklearn.datasets.samples_generator import make_regression 
import pylab
from scipy import stats

# https://dyakonov.org/2018/03/12/логистическая-функция-ошибки/

# Гораздо понятнее статья
# https://towardsdatascience.com/building-a-logistic-regression-in-python-301d27367c24

In [124]:
# шаг алгоритма
alpha = 0.01

In [125]:
# sklearn.datasets.load_iris(return_X_y=False)
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:100, :] 
y = data.target[:100]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [126]:
# теперь всё тоже самое, только корректируем функцию потерь

# Поясняю обозначения:
# a -> hypothesis
# a - y -> loss
# logloss -> J
# d logloss / d w  -> gradient


def gradient_descent_2(alpha, x, y, numIterations):
    """
    Функция реализует алгоритм градиентного спуска. На каждом шаге выводится значение функции потерь
    """
    
    m = x.shape[0] # 100
    theta = np.ones(2) # [ 1.  1.] ВЕСА МОДЕЛИ!!!
    x_transpose = x.transpose() # транспонированная матрица x
    
    for iter in range( 0, numIterations ):
        hypothesis = np.dot(x, theta) # матричное произведение
        
        loss = hypothesis - y
        J = np.sum(loss ** 2) / (2 * m)  # функция потерь
        
#         print( "iter %s | J: %.3f" % (iter, J) )
        
        gradient = np.dot(x_transpose, loss) / m     
        
        theta = theta - alpha * gradient  # update
    
    return theta

In [127]:
def gradient_descent_for_classification (alpha, x, y, numIterations):
   
    theta = np.ones(4) # [ 1.  1.] ВЕСА МОДЕЛИ!!!
    
    for iter in range( 0, numIterations ):
        hypothesis = 1 / (1 + np.exp(-x @ theta.T)) 
        
        loss = hypothesis - y
        
        J = -y*np.log(hypothesis) - (1 - y)*np.log(1 - hypothesis) # функция потерь
        
#         print( "iter %s | J: %.3f" % (iter, J) )
        
        gradient = loss @ x        
        theta = theta - alpha * gradient  # update
    
    return theta

In [128]:
# Веса полученные в ходе расчета градиента
theta = gradient_descent_for_classification(0.01, X, y, 1000)

In [129]:
theta

array([-1.20753712, -2.80312838,  4.78238056,  2.76582937])

In [130]:
y_pred_proba = 1 / (1 + np.exp(-X @ theta.T))
y_pred_proba

array([1.63115321e-04, 8.42900509e-04, 3.79918170e-04, 1.47498407e-03,
       1.39062347e-04, 2.70079945e-04, 5.20486673e-04, 3.92890996e-04,
       2.03801890e-03, 7.79190043e-04, 1.04571102e-04, 8.06628894e-04,
       7.21362178e-04, 3.14380150e-04, 6.62796392e-06, 1.77905763e-05,
       3.98848286e-05, 2.15075345e-04, 1.88720701e-04, 1.49658103e-04,
       6.30652874e-04, 2.61161145e-04, 3.32844654e-05, 2.74342394e-03,
       3.37787211e-03, 1.94199428e-03, 1.10127868e-03, 2.33194226e-04,
       1.91327831e-04, 1.59312957e-03, 1.86821593e-03, 4.21430419e-04,
       3.29045861e-05, 1.41455730e-05, 1.02719768e-03, 1.63968232e-04,
       6.23837785e-05, 1.18998777e-04, 9.55530518e-04, 3.48216074e-04,
       1.50440659e-04, 7.88975795e-03, 5.45690068e-04, 1.44625804e-03,
       1.33502100e-03, 1.25359970e-03, 1.83089492e-04, 6.91342987e-04,
       1.17990903e-04, 3.22362776e-04, 9.99867206e-01, 9.99873001e-01,
       9.99974086e-01, 9.99934700e-01, 9.99971051e-01, 9.99969095e-01,
      

In [131]:
probab_threshold = 0.5

y_predicted_cls = []

for item in y_pred_proba:
    if item >= probab_threshold:
        y_predicted_cls.append(1)
    else:
        y_predicted_cls.append(0)

y_predicted_cls

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [132]:
accuracy = (y_predicted_cls == y).all().mean()
accuracy
# 100% точность то есть массивы совпадают

1.0